[package]
name = "text_area"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
console_error_panic_hook.workspace = true
ratzilla.workspace = true
tui-textarea = { version = "0.7.0", default-features = false, features = ["ratatui"] }
examples-shared.workspace = true
