[package]
name = "animations"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ratzilla = { path = "../../" }
tachyonfx = { version = "0.16.0", default-features = false, features = ["web-time"] }
console_error_panic_hook = "0.1.7"
examples-shared = { path = "../shared" }
