[package]
name = "color-rgb"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
palette.workspace = true
ratzilla.workspace = true
console_error_panic_hook.workspace = true
examples-shared.workspace = true
