[package]
name = "canvas-stress-test"
version = "0.1.0"
edition = "2021"
publish = false
description = "A stress test for the foreground rendering of the CanvasBackend"

[dependencies]
ratzilla.workspace = true
console_error_panic_hook.workspace = true
web-time.workspace = true
compact_str = "0.9.0"
examples-shared.workspace = true
