[package]
name = "canvas-waves"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ratzilla.workspace = true
console_error_panic_hook.workspace = true
tachyonfx.workspace = true
web-time.workspace = true
examples-shared.workspace = true
